name: TacMap
options:
  bundleIdPrefix: com.tacmap
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
  configs:
    Debug:
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  TacMap:
    type: application
    platform: iOS
    sources:
      - path: "TACMAP Current Build"
        excludes:
          - "Resources/Info.plist"
    dependencies:
      - package: MapboxMaps
        product: MapboxMaps
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tacmap.app
        INFOPLIST_FILE: "TACMAP Current Build/Resources/Info.plist"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: TacMap
        SWIFT_ENABLE_EXPLICIT_MODULES: NO
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
        ALWAYS_SEARCH_USER_PATHS: NO
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"

packages:
  MapboxMaps:
    url: https://github.com/mapbox/mapbox-maps-ios.git
    from: "11.0.0"

schemes:
  TacMap:
    build:
      targets:
        TacMap: all
    run:
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
